#!/usr/bin/python

import os, sys
from time import sleep
from lcdproc.server import Server

import threading
import subprocess

from screens import *

if __name__ == "__main__":
    print("pid:{0}".format(os.getpid()))

    try:
        f = open("/tmp/clock", "w")
        f.write("pid\t{0}".format(os.getpid()))
        f.close()
    except:
        pass

    try:
        os.mkfifo("/tmp/clock_fifo")
    except:
        print("FIFO file exists")

    lcd = Server(debug=False)
    lcd.start_session()

    pool = []
    # pool.append(Test(lcd))
    pool.append(LargeClock(lcd))
    # pool.append(MainScreen(lcd, duration=5))
    pool.append(Boinc(lcd, duration=9))
    # pool.append(ClassicClock(lcd, duration=15))
    # pool.append(IPAddr(lcd, duration=2))

    for t in pool:
        t.setDaemon(True)
        t.start()

    fifo = open('/tmp/clock_fifo', 'r')
    while True:
        s = fifo.readline()
        if not s:
            sleep(1)
        else:
            line1 = s
            s = fifo.readline()
            if s:
                line2 = s
            else:
                line2 = ''
            notification = Notify(lcd, line1+line2, 3)
            notification.start()
            notification.join()
            while fifo.readline():
                pass

